right_hand:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Position Controllers ---------------------------------------
  hand_synergy_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_hand_synergy_joint
    pid: {p: 100,  d: 0.5, i: 1.0}